import {
    S3Client,
    GetObjectCommand,
    PutObjectCommand
  } from "@aws-sdk/client-s3";
  
  import {
    SNSClient,
    PublishCommand
  } from "@aws-sdk/client-sns";
  
  const s3 = new S3Client({});
  const sns = new SNSClient({});
  
  const BUCKET = "static-robotic-web-demo";
  const KEY = "events.json";
  
  const TOPIC_ARN =
    "arn:aws:sns:us-east-1:755610857977:robotic-subscribers";
  
  const corsHeaders = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type",
    "Access-Control-Allow-Methods": "OPTIONS,POST"
  };
  
  async function streamToString(stream) {
    return await new Response(stream).text();
  }
  
  export const handler = async (event) => {
  
    if (
      event.httpMethod === "OPTIONS" ||
      event.requestContext?.http?.method === "OPTIONS"
    ) {
      return {
        statusCode: 200,
        headers: corsHeaders,
        body: ""
      };
    }
  
    try {
  
      const body = JSON.parse(event.body);
  
      let events = [];
  
      try {
  
        const response = await s3.send(
  
          new GetObjectCommand({
  
            Bucket: BUCKET,
            Key: KEY
  
          })
  
        );
  
        const content = await streamToString(response.Body);
  
        events = JSON.parse(content);
  
      } catch {
  
        console.log("events.json not found. Creating new file.");
  
      }
  
      events.push({
  
        name: body.name,
        email: body.email,
        message: body.message,
        createdAt: body.createdAt
  
      });
  
      await s3.send(
  
        new PutObjectCommand({
  
          Bucket: BUCKET,
          Key: KEY,
          Body: JSON.stringify(events, null, 2),
          ContentType: "application/json"
  
        })
  
      );
  
      await sns.send(
  
        new PublishCommand({
  
          TopicArn: TOPIC_ARN,
  
          Subject: "🤖 New RoboTech AI Contact Form",
  
          Message: `
  A new contact form has been submitted.
  
  -------------------------------------
  
  Name:
  ${body.name}
  
  Email:
  ${body.email}
  
  Message:
  ${body.message}
  
  Submitted At:
  ${body.createdAt}
  
  -------------------------------------
  
  This notification was automatically generated by RoboTech AI.
  `
  
        })
  
      );
  
      return {
  
        statusCode: 200,
  
        headers: corsHeaders,
  
        body: JSON.stringify({
  
          success: true,
          message: "Event registered successfully."
  
        })
  
      };
  
    } catch (err) {
  
      console.error(err);
  
      return {
  
        statusCode: 500,
  
        headers: corsHeaders,
  
        body: JSON.stringify({
  
          success: false,
          error: err.message
  
        })
  
      };
  
    }
  
  };